// src/App.svelte
<script>
  import Home from "./routes/Home.svelte";
  import Login from "./routes/Login.svelte";
  import Dashboard from "./routes/Dashboard.svelte";
  import Register from "./routes/Register.svelte";
  import { router } from "./router.svelte.js";
  import Navbar from "./components/Navbar.svelte";
</script>

<div style="width: 100%;">
  <Navbar />
  <main>
    {#if router.currentPath === "/"}
      <Home />
    {:else if router.currentPath === "/login"}
      <Login />
    {:else if router.currentPath === "/register"}
      <Register />
    {:else if router.currentPath === "/dashboard"}
      <Dashboard />
    {:else}
      <article>
        <h1>404</h1>
        <p>Página no encontrada</p>
      </article>
    {/if}
  </main>
</div>

// old-react/src/App.jsx
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import Home from './views/Home'
import Login from './views/Login'
import Register from './views/Register'
import Dashboard from './views/Dashboard'

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/login" element={<Login />} />
        <Route path="/register" element={<Register />} />
        <Route path="/dashboard" element={<Dashboard />} />
      </Routes>
    </Router>
  )
}

export default App
